version: '3.9'

services:
  backend:
    image: mdma-backend:${IMAGE_TAG}
    container_name: mdma-backend
    restart: unless-stopped
    networks:
      - postgres
    environment:
      MDMA_DATABASE_DSN: postgres://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres/postgres?sslmode=disable&connect_timeout=10
      MDMA_JWT_SECRET: ${JWT_SECRET}

networks:
  postgres:
    external: true